version: '3.8'

services:
  backup:
    build: .
    environment:
      - B2_KEY_ID=your_key_id_here
      - B2_KEY=your_application_key_here
      - B2_BUCKET_NAME=your_bucket_name_here
      - MONGO_CONTAINER_NAME=mongo
      - MONGO_URI=mongodb://localhost:27017
      - BACKUP_PATH=/backup
    volumes:
      - ./backups:/backup
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: ${MONGO_CONTAINER_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backup_network

volumes:
  mongodb_data:

networks:
  backup_network:
    driver: bridge 